name: Adrian Sampson
author: Adrian Sampson
url: https://www.cs.cornell.edu/~asampson
base: '/~asampson'
twitter: '@samps'
email: 'asampson@cs.cornell.edu'
logo: https://www.cs.cornell.edu/~asampson/media/icon/favicon512.png
ghrepo: https://github.com/sampsyo/home

# Use a prefix for the local server. Eventually, replace `base` with this.
baseurl: '/~asampson'

markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
    enable_coderay: false
    auto_ids: true
    entity_output: symbolic
    math_engine: null
highlighter: none

sass:
    style: compressed
    sass_dir: _source

exclude:
    - bower_components
    - node_modules
    - package.json
    - bower.json
    - Makefile

permalink: /blog/:title.html

defaults:
    -
        scope:
            path: ""
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
    -
        scope:
            type: pages
        values:
            permalink: /:path/:basename:output_ext

navigation:
    - title: home
      link: /
    - title: research
      link: /research.html
    - title: teaching
      link: /teaching.html
    - title: blog
      link: /blog/
    - title: contact
      link: /contact.html

redirect:
    files/enerjproofs.pdf: media/enerjproofs.pdf

# Rendered drafts.
collections:
    drafts:
        output: true
        permalink: /blog/drafts/:slug.html
